[target.riscv32imac-unknown-none-elf]
runner = "./flash.bat target/riscv32imac-unknown-none-elf/debug/esp32-mender-client"

[env]
ESP_LOG="INFO"
ESP_WIFI_CONFIG_PHY_ENABLE_USB = "false"
MENDER_CLIENT_WIFI_SSID = "ssid"
MENDER_CLIENT_WIFI_PSK = "psk"

[build]
rustflags = [
  # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
  # NOTE: May negatively impact performance of produced code
  "-C", "force-frame-pointers",
]

target = "riscv32imac-unknown-none-elf"

[unstable]
build-std = ["alloc", "core"]