on: [push, pull_request]

name: CI
env:
  MENDER_CLIENT_WIFI_SSID: "ssid"
  MENDER_CLIENT_WIFI_PSK: "psk"

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rustup
        run: |
          sudo apt-get update
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
          echo "export PATH=\$HOME/.cargo/bin:\$PATH:/usr/bin" >> $GITHUB_ENV
        shell: bash

      - name: Setup Rust Environment
        run: |
          rustup component add rustfmt
          rustup component add clippy
          rustup target add riscv32imc-unknown-none-elf
          rustup target add riscv32imac-unknown-none-elf
          sudo apt-get install build-essential
          sudo apt-get install -y libudev-dev
          sudo apt install pkg-config
          cargo update
          export PATH=$(pwd)/aarch64-linux-musl-cross/bin:$PATH
        shell: bash

      - name: Rustfmt
        run: cargo fmt --all -- --check
        continue-on-error: false

      #- name: Clippy (esp32c2)
      #  run: cargo clippy --target riscv32imc-unknown-none-elf --features esp32c2 -- -D warnings
      #  continue-on-error: false

      - name: Clippy (esp32c3)
        run: cargo clippy --target riscv32imc-unknown-none-elf --features esp32c3 -- -D warnings
        continue-on-error: false

      #- name: Clippy (esp32h2)
      #  run: cargo clippy --target riscv32imc-unknown-none-elf --features esp32h2 -- -D warnings
      #  continue-on-error: false

      - name: Clippy (esp32c6)
        run: cargo clippy --target riscv32imac-unknown-none-elf --features esp32c6 -- -D warnings
        continue-on-error: false

      #- name: Clippy (ESP32)
      #  run: cargo clippy --target xtensa-esp32-none-elf --features esp32 -- -D warnings
      #  continue-on-error: false    

      #- name: Clippy (esp32s2)
      #  run: cargo clippy --target xtensa-esp32s2-none-elf --features esp32s2 -- -D warnings
      #  continue-on-error: false    

      #- name: Clippy (esp32s3)
      #  run: cargo clippy --target xtensa-esp32s3-none-elf --features esp32s3 -- -D warnings
      #  continue-on-error: false               
